name: Server-Side Rendering

on: push

jobs:
  build:
    if: secrets.VERCEL_TOKEN == ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install
        run: npm install

      - name: Build server bundle
        run: npm run build-server

      - name: Compile test
        run: npx tsc test/ssr/index.ts --rootDir ./test/ --outDir dist_test/

      - name: Run test
        run: node dist_test/ssr/
